name: test

on:
  push:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
    - name: Setup dummy SECRET file
      run: |
        touch SECRETS.py
        echo "PSQL_URL = 'postgresql+asyncpg://user:password@localhost:5432/database'" > SECRETS.py
        echo "OPENWEATHERMAP_KEY = '1234qwertz'" > SECRETS.py
        echo "SECRET_KEY = '1234qwertz'" > SECRETS.py
        echo "SERVERSTATS_SETTINGS = {'hosting_id': '123', 'token': '1234qwertz'}" > SECRETS.py
    - name: Test with pytest
      run: |
        pytest --cov-report html --cov=api
